goharbor/website

themes/harbor/layouts/partials/footer.html

Modifying copyright footer to reflect CNCF donation.

Update copyright footer

---

content/blogs/harbor-1.6.0-release.md

This will add a blog post with details for the 1.6.0 release.

Add Harbor 1.6.0 blog post

---

config.yaml

This will change the URLs in the footer to be updated with the correct ones.

Fix footer links

---

content/blogs/harbor-at-kubecon-seattle-2018.md

Quick blog post re: Harbor events going on in Seattle at KubeCon 2018.

[blog post] KubeCon 2018 Seattle

---

content/blogs/zh/harbor-1.6.0-release.md

Signed-off-by: Steven Zou <szou@vmware.com>

Add zh blog of Harbor V1.6.0

---

content/blogs/welcome-new-maintainers-feb-2019.md

Adding the new maintainers blog post
Signed-off-by: Jonas Rosland <jrosland@vmware.com>

Adding new maintainers blog

---

content/blogs/harbor-1.7.0-release.md
content/blogs/harbor-moves-to-incubation.md
content/blogs/welcome-new-maintainers-march-2019.md
themes/harbor/data/userDocuments.json
themes/harbor/layouts/partials/single/template-community.html

Small updates, fixed links and blog post should now be live.

Small updates to correct links and publish blog

---

content/blogs/announcing-harbor-1.8.md

Adding Harbor 1.8 release blog
Signed-off-by: Jonas Rosland <jrosland@vmware.com>

Adding Harbor 1.8 release blog

---

content/blogs/announcing-harbor-1.8.md

Signed-off-by: Jonas Rosland <jrosland@vmware.com>

Timezone change for announcement blog

---

config.yaml
themes/harbor/layouts/partials/home/hero.html

updating the Harbor website with mission statement and including a link to the K8s deployment

updating Harbor website

---

config.toml
layouts/partials/navbar.html

For some reason the SVG image isn't working for the navbar icon. This PR switches to the PNG until I can figure out a solution for using the SVG.

Fix navbar image

---

content/blog/introducing-the-harbor-operator.md

This will add the Harbor operator blog.

Add Harbor Operator blog

---

config.toml
layouts/partials/footer.html

This PR brings the copyright text in the site footer in accordance with CNCF/LF requirements.

Update copyright footer text

---

layouts/index.redirects

Fix /docs/latest redirect

---

layouts/index.redirects

Adds a forced 301 redirect to the /docs path

Redirect fix

---

load-docs.sh

This will make it possible to view the latest master version of the docs over at https://goharbor.io/docs/master, without adding a link to it in the dropdown menu.
This is meant for core maintainers and contributors to be able to view the docs of a new release before the release is cut.

Add functionality to view master branch of docs on the live site

---

config.toml

Add CNCF webinar to the front page

---

layouts/shortcodes/social.html

Took me a while to figure out getting into the slack channel, so I've added a self-service link to get on the CNCF Slack.

Social: Some more help in on-boarding to Slack

---

load-docs.sh

This will add a new load-docs function to work with the website repo, and create and "edge" docs page for new docs.

Add new load docs

---

load-docs.sh

Fix load docs

---

docs/administration/managing-users/user-permissions-by-role.md
docs/build-customize-contribute/use-make.md

Merge recent docs changes from main repo

Merge recent docs changes from main repo

---

README.md
netlify.toml
package-lock.json

Add new documentation guidelines to README

---

docs/install-config/quick-install-script.md

Changes password in the docs such that it matches the one of the quickinstall script.
This is equivalent to my [orginal harbor PR](https://github.com/goharbor/harbor/pull/11403)
Signed-off-by: Tim Gretler <gretler.tim@gmail.com>

Update quickinstall docs

---

docs/administration/upgrade/_index.md
docs/install-config/quick-install-script.md

Update password in docs to match install script and fix typo in filename

update typos in2.0 docs

---

layouts/partials/github-info.html

Fix the CNCF badge to say Graduated

---

docs/install-config/download-installer.md

fix https://github.com/goharbor/harbor/issues/12486, make sample more accurate

update gpg sample

---

docs/install-config/run-installer-script.md

run installer script need contains the content about trivy adapter
Signed-off-by: DQ <dengq@vmware.com>

Add Doc for Trivy

---

docs/install-config/configure-yml-file.md
docs/install-config/harbor-ha-helm.md

add document for redis sentinel mode

add document for redis sentinel mode

---

docs/administration/configure-proxy-cache/_index.md
docs/working-with-projects/working-with-images/pulling-pushing-images.md

add windows support and update proxy cache docs

---

docs/_index.md

Signed-off-by: Daniel Jiang <jiangd@vmware.com>

Bump up the versions on index page for 2.1

---

docs/install-config/configure-yml-file.md

https://github.com/goharbor/website/issues/99

corrected subkey from certificate to dir for internal_tls key

---

config.toml

update config file for 2.1

---

docs/administration/upgrade/_index.md

fix copy harbor.yml in update doc

fix update doc

---

docs/working-with-projects/working-with-images/preheat-images.md

I suggested a change in #113 , which turned out to be wrong. This reverts that change.

Fix preheat link

---

docs/install-config/configure-user-settings-cli.md

fix https://github.com/goharbor/website/issues/116
api url change from /api to /api/v2.0

update api url in configure-user-settings-cli.md

---

docs/administration/configure-proxy-cache/_index.md

And give an existing image as a working example
Fixes https://github.com/goharbor/harbor/issues/13222

Fix up how to pull official images thrugh proxy

---

docs/administration/vulnerability-scanning/import-vulnerability-data.md
docs/install-config/run-installer-script.md

Add Clair deprecation notes to site

---

.backportrc.json
README.md

Add backport config and update readme

---

docs/administration/configure-proxy-cache/_index.md

update proxy cache for new  docker policy

---

docs/administration/vulnerability-scanning/import-vulnerability-data.md
docs/install-config/run-installer-script.md

fix clair message links

---

docs/administration/vulnerability-scanning/import-vulnerability-data.md
docs/install-config/run-installer-script.md

- Add Clair depreecation notes to site (234adc02)
- fix clair message links (984c777a)

[release-2.1.0] Add Clair depreecation notes to site (234adc02) | fix clair message links (984c777a)

---

layouts/404.html

Add custom 404 page

---

docs/working-with-projects/working-with-images/create-tag-retention-rules.md

close https://github.com/goharbor/harbor/issues/13397
the example of retention is not correct, rules are using `or` algorithm.

fix(retention) bad example

---

docs/administration/managing-users/user-permissions-by-role.md

This change needs to be added to the 1.10, 2..0.0, and 2.1.0 branch.
Closes https://github.com/goharbor/harbor/issues/13389

Update immutability rules user permissions

---

docs/administration/managing-users/user-permissions-by-role.md

Backports the following commits to release-1.10:
- Update immutability rules user permissions (7bc5983b)

[release-1.10] Update immutability rules user permissions (7bc5983b)

---

docs/administration/managing-users/user-permissions-by-role.md

Backports the following commits to release-2.0.0:
- Update immutability rules user permissions (7bc5983b)

[release-2.0.0] Update immutability rules user permissions (7bc5983b)

---

docs/administration/managing-users/user-permissions-by-role.md

- Update immutability rules user permissions (7bc5983b)

[release-2.1.0] Update immutability rules user permissions (7bc5983b)

---

layouts/shortcodes/community-info.html

Add temporary fix for the office hours timing

---

docs/build-customize-contribute/compile-guide.md

Signed-off-by: sluetze <13255307+sluetze@users.noreply.github.com>
partly fixes #142

bumped up golang versions

---

docs/administration/configuring-replication/create-replication-endpoints.md

close https://github.com/goharbor/harbor/issues/13688

fix(doc) remove bad slash in doc

---

assets/sass/style.sass

Fix figures in tables so they show up a normal size

---

docs/build-customize-contribute/style-guide.md
layouts/shortcodes/table.html

Add style guide and table shortcode

---

docs/README.md
docs/administration/_index.md
docs/administration/user-defined-OCI-artifact/_index.md

Signed-off-by: Yiyang Huang huangyiyang.huangyy@bytedance.com
/cc @steven-zou @xaleeks

doc: add docs for user-defined OCI artifact

---

docs/install-config/configure-yml-file.md

Update trivy yml skip_update config option information

---

docs/working-with-projects/working-with-images/pulling-pushing-images.md

Closes https://github.com/goharbor/harbor/issues/13646

Add docs for resolving lost notary keys

---

docs/administration/vulnerability-scanning/_index.md

Closes https://github.com/goharbor/harbor/issues/13482

Exporting vulnerability scans from api

---

docs/administration/configure-authentication/ldap-auth.md

Fixes #181 
This should be updated in all release versions of the docs

Add more explicit information about LDAP configuration

---

docs/administration/metrics/_index.md
docs/install-config/configure-yml-file.md

Add prometheus metric docs

---

content/blog/harbor-2.2.md

This will add the blog post for the 2.2 announcement

Add 2.2 blog

---

content/blog/harbor-2.2.md

Fix minor spelling error

---

docs/administration/metrics/_index.md

Fixes https://github.com/goharbor/harbor/issues/13185

Add docs for Kubernetes metrics

---

docs/install-config/reconfigure-manage-lifecycle.md

include data/redis in list of things to remove

---

docs/install-config/download-installer.md

fix https://github.com/goharbor/harbor/issues/14403
use code style

fix dash in download-installer.md

---

docs/install-config/download-installer.md

Backports the following commits to release-1.10:
- fix dash in download-installer.md (99297ca9)

[release-1.10] fix dash in download-installer.md (99297ca9)

---

docs/install-config/download-installer.md

Backports the following commits to release-2.2.0:
- fix dash in download-installer.md (99297ca9)

[release-2.2.0] fix dash in download-installer.md (99297ca9)

---

docs/install-config/download-installer.md

Backports the following commits to release-2.0.0:
- fix dash in download-installer.md (99297ca9)

[release-2.0.0] fix dash in download-installer.md (99297ca9)

---

docs/install-config/download-installer.md

- fix dash in download-installer.md (99297ca9)

[release-2.1.0] fix dash in download-installer.md (99297ca9)

---

docs/build-customize-contribute/developer-guide-i18n.md

Update supported languages

---

docs/build-customize-contribute/customize-look-feel.md

Include warning about headerBgColor on customize docs

---

docs/build-customize-contribute/developer-guide-i18n.md

Add localization contributor process

---

docs/administration/configure-proxy-cache/_index.md

Related to https://github.com/goharbor/harbor/pull/14579

Add docker registry to proxy cache docs

---

docs/administration/configure-proxy-cache/_index.md

Backports the following commits to release-2.2.0:
- Merge pull request #215 from a-mccarthy/update-14579 (#215)

[release-2.2.0] Merge pull request #215 from a-mccarthy/update-14579 (#215)

---

docs/administration/metrics/_index.md

Fixes: https://github.com/goharbor/harbor/issues/14468
Pulling information from the community proposal, https://github.com/goharbor/community/blob/4aea46513c1401589518e9701c6402c9dc275527/proposals/new/metrics_in_jobservice.md. 
Need to verify with a running instance, once this feature is complete. Dev work happing as part of, https://github.com/goharbor/harbor/issues/14469

Add jobservice metrics information

---

docs/install-config/configure-user-settings-cli.md

Fixes: #https://github.com/goharbor/harbor/issues/15043

Add documentation for declarative user setting configuration

---

.backportrc.json
README.md
config.toml
docs/_index.md

Signed-off-by: Orlin Vasilev <ovasilev@vmware.com>

Release 2.3.0 documentation

---

docs/administration/upgrade/_index.md
docs/build-customize-contribute/use-make.md

Update upgrade page

---

docs/administration/upgrade/_index.md
docs/build-customize-contribute/use-make.md

Backports the following commits to release-2.3.0:
- Update upgrade page (1f6614cd)

[release-2.3.0] Update upgrade page (1f6614cd)

---

docs/install-config/_index.md

Update postgres and redis versions

---

docs/administration/managing-users/user-permissions-by-role.md

https://cloud-native.slack.com/archives/CC1E09J6S/p1623940421220200 showed, this permission is missing in the Table.

Added "Delete Project" Permission

---

docs/build-customize-contribute/e2e-api-python-based-scripting-guide.md

Signed-off-by: Danfeng Liu <danfengl@danfengl-a01.vmware.com>

Add more description to E2E test guide book

---

layouts/shortcodes/community-info.html

Signed-off-by: Orlin Vasilev <ovasilev@vmware.com>

Change the infor for community meetings and office hours

---

docs/build-customize-contribute/configure-swagger.md

Signed-off-by: 0xff-dev <stevenshuang521@gmail.com>

Update outdated swagger info

---

docs/install-config/customize-token-service.md

I was struggling with token service customizations. After digging thru helm charts, core service code and prepare tool figured out that one directory reference was missing

token service customizations

---

docs/administration/metrics/_index.md

fix typo instead of origin PR https://github.com/goharbor/website/pull/223

fix typo Scraping

---

docs/build-customize-contribute/registry-landscape.md

bringing this back in sync with #144

Update Quay capabilities

---

layouts/shortcodes/community-info.html

Update link to community meeting notes

---

load-docs.sh

Signed-off-by: Jonas Rosland <jrosland@vmware.com>

Update load-docs.sh to use main instead of master branch

---

config.toml

fix Artwork broken link

---

.backportrc.json
README.md

update readme with changes for main branch

---

content/blog/harbor-sig-docs-launch.md

add blog for sig docs launch

---

docs/administration/metrics/_index.md

Add missing metrics for registry and show better how the histogram metrics look like

Add missing metrics

---

docs/administration/managing-users/user-permissions-by-role.md

Small Grammatical change to the tech-docs

Resolved a small error in the documentation

---

docs/working-with-projects/working-with-images/create-tag-retention-rules.md

Updated a word in the example section of the tech-doc

updated a word in the example section of the tech-doc

---

content/blog/harbor-at-fosdem-2022.md

Add blog post for FOSDEM talk by Orlix

---

CODEOWNERS

Add CODEOWNERS from sig-community and sig-docs

---

.backportrc.json
config.toml
docs/_index.md

Update docs for 2.5

---

content/blog/cosign-2.5.0.md

Add video for cosign demo in the blog

---

docs/working-with-projects/working-with-images/managing-helm-charts.md

Signed-off-by: Shengwen Yu <yshengwen@vmware.com>

fix: update command for chartmuseum/helm-push plugin when helm version >= v3.7.0

---

docs/working-with-projects/working-with-images/create-tag-retention-rules.md

Fix number of rules
Fix results : add `4.4-your_repo-prod` because of second rule

Fix exemple 5 results

---

docs/administration/backup-restore/_index.md

Add several links to the Velero offical docs to cover the basic concepts, troubleshooting and supported providers
Signed-off-by: Wenkai Yin(尹文开) <yinw@vmware.com>

Update the doc for backing up and restoring Harbor with Velero

---

docs/administration/backup-restore/_index.md

fixes https://github.com/goharbor/harbor/issues/16903

Edits for Velero tutorial

---

docs/install-config/configure-yml-file.md

fixes: https://github.com/goharbor/harbor/issues/17078
I've also made edits to the related Wiki page - https://github.com/goharbor/perf/wiki/Cache-layer. Please also review that page. Specifically, I've added more details to the architecture section to describe the diagram.

Add cache layer docs

---

.backportrc.json
config.toml
docs/_index.md
docs/administration/upgrade/_index.md

Update main for 2.6 release

---

docs/install-config/installation-prereqs.md

Signed-off-by: yminer <yminer@vmware.com>

update support docker compose v2 on release-2.6.0

---

docs/install-config/installation-prereqs.md

Signed-off-by: yminer <yminer@vmware.com>

update support docker compose v2

---

docs/install-config/harbor-ha-helm.md

Fixes: https://github.com/goharbor/harbor/issues/17566
Signed-off-by: chlins <chenyuzh@vmware.com>

fix: correct the install command for harbor ha helm installation

---

content/blog/harbor-2.6.md

fix: broken link in blog for 2.6

---

docs/administration/configure-authentication/_index.md

Signed-off-by: yminer <yminer@vmware.com>

fix OIDC typo

---

docs/build-customize-contribute/ui-contribution-get-started.md

The example is wrong for the newer setup of the portal. Example is from README.md in src/portal
Signed-off-by: Sören Rohweder <s.rohweder@blage.net>

Change proxy.config.json example

---

docs/administration/configure-proxy-cache/_index.md

Signed-off-by: stonezdj <stonezdj@gmail.com>

Can ignore library for dockerhub proxy cache

---

.backportrc.json
config.toml
docs/_index.md
docs/administration/upgrade/_index.md

Signed-off-by: stonezdj <daojunz@vmware.com>

Update main for 2.7.0 release

---

docs/install-config/configure-yml-file.md

1, add conn_max_lifetime and conn_max_idle_time for DB 2, security_check for trivy
Signed-off-by: Wang Yan <wangyan@vmware.com>

update harbor.yml for v2.7

---

docs/administration/garbage-collection/_index.md

Signed-off-by: yminer <yminer@vmware.com>

update tab name to clean up

---

docs/administration/user-defined-OCI-artifact/_index.md

Signed-off-by: Shengwen Yu <yshengwen@vmware.com>

[Cherry-pick] doc: correct the malformat quote

---

docs/administration/user-defined-OCI-artifact/_index.md

Signed-off-by: Shengwen Yu <yshengwen@vmware.com>

doc: correct the malformat quote

---

docs/build-customize-contribute/developer-guide-i18n.md

Update the doc because of https://github.com/goharbor/harbor/pull/18070
Signed-off-by: AllForNothing <sshijun@vmware.com>

Update Developing for Internationalization sectin

---

docs/administration/backup-restore/_index.md
docs/administration/robot-accounts/_index.md
docs/working-with-projects/project-configuration/configure-webhooks.md
docs/working-with-projects/project-configuration/create-robot-accounts.md

I've replaced `disable` with `deactivate` for 2.6.0 branch. Fixes #303.

Replaced `disable` with `deactivate`

---

docs/install-config/_index.md

Signed-off-by: PaarthAgarwal <paarth.agarwal.mec20@itbhu.ac.in>
Should fix #403. I might need to open another PR for the main branch.

Fixed configure user settings link

---

assets/sass/helpers.sass
docs/install-config/configure-yml-file.md

Signed-off-by: PaarthAgarwal <paarth.agarwal.mec20@itbhu.ac.in>
Fixes #162.
Before:
After the fix:
I've added fixed-layout and word-break properties for the table. Apologies for this mess of commits 😅.

Fixed table size bug

---

.github/auto-assignees.yml
.github/workflows/auto_assign_prs.yml

Add auto-assignees for PRs

---

docs/install-config/_index.md

Signed-off-by: PaarthAgarwal <paarth.agarwal.mec20@itbhu.ac.in>
Closes https://github.com/goharbor/website/issues/403. Based on https://github.com/goharbor/website/pull/412#issuecomment-1420847322.

Fixed configure user settings link for main

---

docs/build-customize-contribute/ui-contribution-get-started.md

1. Update Developing the Harbor Frontend section to improve the setup process for developing the Harbor UI
After update:
---
title: Developing the Harbor Frontend
---
If you already have a harbor backend environment, you can build a frontend development environment with the following
configuration.
1. Open the terminal and run the following command to copy "proxy.config.mjs.temp" file to "proxy.config.mjs".
```sh
cd harbor/src/portal
cp proxy.config.mjs.temp proxy.config.mjs
```
**NOTE:** You should specify an available Harbor hostname. And you can specify the agent if you work behind a
corporate proxy.
```js
import HttpsProxyAgent from 'https-proxy-agent';
// Define the proxy configuration
const HarborProxyConfig = [
{
"context": [
"/api",
"/c",
"/i18n",
"/chartrepo",
"/LICENSE", …
```

Update Developing the Harbor Frontend section

---

docs/working-with-projects/project-configuration/configure-webhooks.md

Update the mismatch webhook example JSON payload for artifact pushed.

fix: correct the mismatch example json payload for artifact pushed

---

.backportrc.json
config.toml
docs/_index.md
docs/administration/upgrade/_index.md

Update the main branch as the Harbor 2.8.0 has been released

Update main branch for the 2.8.0 release

---

docs/working-with-projects/working-with-images/managing-helm-charts.md

Reference https://github.com/helm/helm/releases/tag/v3.7.0
Signed-off-by: mathumohan25 <65863465+mathumohan25@users.noreply.github.com>

Updated the docs respect to 3.7.0 version changes

---

docs/working-with-projects/working-with-images/managing-helm-charts.md

See https://github.com/chartmuseum/helm-push#push-tgz-package

fix helm push command

---

docs/install-config/configure-https.md

based on https://github.com/goharbor/website/pull/360

Fix wording in docs CRS -> CSR

---

docs/working-with-projects/working-with-images/create-tag-retention-rules.md

1. Fixes https://github.com/goharbor/harbor/issues/18852

Update doc on where tag retention rules are defined and how you can apply them

---

docs/working-with-projects/working-with-images/pulling-pushing-images.md

1. Fixes https://github.com/goharbor/harbor/issues/18744

Add sentence about how to view Registry Certificate button.

---

.backportrc.json
config.toml
docs/_index.md
docs/administration/upgrade/_index.md

Update main branch for the 2.9.0 release

Update main branch for the 2.9.0 release

---

docs/_index.md

[Cherry-pick #493](https://github.com/goharbor/website/pull/494)

 [Cherry-pick]Correct the title for 2.9 release

---

docs/_index.md

Correct the title for 2.9 release

Correct the title for 2.9 release

---

docs/working-with-projects/project-configuration/create-robot-accounts.md

Corrected grammar on sentence.

Update Docs fix typo in create-robot-accounts.md

---

docs/administration/upgrade/helm-upgrade.md

Hi
I assume that `process` is the correct word, not `progress`. At least that's how I understand the context of the text.
If I'm wrong, please apology and close the PR.
Br
Thomas

Probably wrong word used in helm-upgrade.md

---

docs/administration/metrics/_index.md

Merge this after this PR is merged which changes the folder name: https://github.com/goharbor/harbor/pull/16661

Fix grafana dashboard link spelling

---

docs/_index.md

change version from 2.9 to 2.10

Update version in _index.md

---

docs/administration/upgrade/_index.md

Update upgrade matrix in main branch

Update upgrade matrix in main

---

docs/install-config/harbor-compatibility-list.md

Add Yes to the Cyberwatch scanner Evaluation, based on the demonstration we made on June 14th 2023 (https://github.com/goharbor/community/wiki/Harbor-Community-Meetings#june-14-2023)

Confirm Cyberwatch scanner eval after community meeting

---

docs/working-with-projects/working-with-oci/working-with-helm-oci-charts.md

Revert "Typo Fix"

---

docs/administration/upgrade/_index.md

Fix links that are incorrect for version
- v2.3.0
- v2.0.0

Fix links that are incorrect for version(v2.3.0, v2.0.0)

---

docs/administration/p2p-preheat/_index.md

docs: update the supported matrix between harbor and dragonfly
Fixes: https://github.com/goharbor/harbor/issues/20970

docs: update the supported matrix between harbor and dragonfly

---

docs/_index.md
docs/administration/upgrade/_index.md

Create document for Harbor v2.12.0

Add Harbor 2.12.0 document

---

docs/administration/garbage-collection/_index.md

fixing typo in the page garbage-collection/_index.md

---

docs/administration/configuring-replication/create-replication-rules.md

fixing typo in the page create-replication-rules

---

docs/install-config/installation-prereqs.md

docs: update content

---

docs/install-config/_index.md

Update component version
