goharbor/website

- themes/harbor/layouts/partials/single/template-community.html
Replace hello@goharbor.io with a link to send an email to the user distribution list, or reach out to us on Slack.
> Remove hello@goharbor.io

- config.yaml
- content/blogs/harbor-1.7.0-release.md
- themes/harbor/layouts/partials/single/template-community.html
I tried to join on slack, only to find that I was trying to join a different cncf... these are not the links for the cncf that you think they are :p 
cncf.slack.com is for the community of the Canadian National Christian Foundation
cncf.slack.io is not registered: ```$ host cncf.slack.io
Host cncf.slack.io not found: 3(NXDOMAIN)```
> Fix links to #harbor on cloud-native.slack.com

- config.yaml
- content/blogs/contributing.md
This will fix the footer's links to the distribution lists, and also include proper links in the "Contributing 101" blog.
> fix distribution list links

- layouts/_default/_markup/render-image.html
Currently, getting out of an image display modal requires clicking the small "x" icon in the upper right. This PR will enable people to get out of the modal by clicking anywhere outside of the image.
> Improve modal image click away

- Makefile
- config.toml
- layouts/partials/navbar.html
- load-docs.sh
This will add a new function to automatically pull down docs from versioned branches, instead of using a submodule with versioned folders.
> Add new docs generating function

- layouts/partials/docs/menu.html
One of the undiscovered issues with the current versioning scheme is that docs sections are doubled in the sidebar. This PR fixes that.
> Fix docs sidebar menu

- assets/sass/helpers.sass
- layouts/_default/baseof.html
- layouts/partials/docs/layout.html
- layouts/partials/docs/sidebar.html
This PR fixes two rendering issues. On different docs pages the width of the main content section (the middle section) varies because the Bulma column doesn't have a specified width. This PR specifies a width and eliminates the issue.
Another issue is that pages like https://goharbor.io/docs/1.10/working-with-projects don't have a "sticky" footer because the page content isn't pushing the footer down to the bottom. This PR addresses that as well.
> Fix docs main width and sticky footer

- layouts/partials/home/hero.html
This fixes the broken links on the frontpage, found by @lachlanmunro at https://github.com/goharbor/harbor/issues/10609#issuecomment-619045055
> Fix docs links on frontpage

- config.toml
- load-docs.sh
This will change the behavior of load-docs.sh to use the local branches in /website instead of the docs branches in /harbor
> Make load-docs.sh use local branches

- docs/administration/upgrade/_index.md
This commit bumps the versions in upgrade path, from 1.9 -> 2.0 to 1.10 -> 2.1.
This also adjusts the Notes section to add a note about data extraction after upgrading to v2.0
Signed-off-by: Daniel Jiang <jiangd@vmware.com>
> Update version in upgrade doc

- docs/administration/configure-proxy-cache/_index.md
- update proxy cache for new  docker policy (88d6f323)
- correct rate limitor language (26b9e91f)
> [release-2.1.0] update proxy cache for new  docker policy (88d6f323) | correct rate limitor language (26b9e91f)

- docs/administration/configure-proxy-cache/_index.md
This also needs to be pushed to the 2.1 release branch
> Fix proxy cache example to include when to /library is needed

- docs/administration/configure-proxy-cache/_index.md
- Fix proxy cache example to include pulling from single level repositories. (9228db27)
> [release-2.1.0] Fix proxy cache example to include pulling from single level repositories. (9228db27)

- docs/build-customize-contribute/configure-swagger.md
it looks like the `swagger.yaml` file actually lives in the `api` directory, not the `docs` directory: https://github.com/goharbor/harbor/blob/master/api/swagger.yaml
> fix: update location of swagger.yaml file

- docs/administration/configure-proxy-cache/_index.md
- docs/administration/configuring-replication/create-replication-endpoints.md
Add proxy cache support for 
- AWS Elastic Container Registry
- Azure Container Registry
- Google Container Registry
- Quay
> Add proxy cache support for new registries

- docs/administration/configure-proxy-cache/_index.md
It seems that a commit (9228db27) last year made the proxy cache documentation inaccurate. I recently setup a proxy cache solution with Harbor and found the docs confusing. So the commit in this PR fixes the example.
Evidence of the correct usage:
```
~ ❯❯❯ docker pull <omitted domain>/proxy-cache/library/nginx
Using default tag: latest
latest: Pulling from proxy-cache/library/nginx
Digest: sha256:d2925188effb4ddca9f14f162d6fba9b5fab232028aa07ae5c1dab764dca8f9f
Status: Image is up to date for <omitted domain>/proxy-cache/library/nginx:latest
<omitted domain>/proxy-cache/library/nginx:latest
```
vs the way the docs currently indicate:
```
~ ❯❯❯ docker pull <omitted domain>/library/nginx
Using default tag: latest
Error response from daemon: unknown: repository library/nginx not found
```
> fix invalid proxy cache single level pull example

- docs/install-config/configure-yml-file.md
This PR fix the documenation about the metric configuration.
When `enable`is used i got the following error:
```
Traceback (most recent call last):
File "main.py", line 15, in <module>
cli()
File "/usr/lib/python3.6/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/usr/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python3.6/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File …
```
> fixed metric enable key

- docs/install-config/configure-yml-file.md
Backports the following commits to release-2.2.0:
- fixed metric enable key (8c014499)
> [release-2.2.0] fixed metric enable key (8c014499)

- docs/administration/upgrade/_index.md
Added wording to make it more obvious that the installer package needs to be extracted after download and added link to the original guide on all the details on it for online vs offline etc. as a reminder.
> Updated Upgrade Guide

- docs/build-customize-contribute/registry-landscape.md
[Quay](https://projectquay.io) is an Open Source project, that is currently submitted as CNCF sandbox. It actually does feature Tag Retention policies (I am unsure what partial refers to) and with Clair v4 it also has the ability to plug additional scanners into the vulnerability framework.
> Updating Quay capabilities

- docs/administration/metrics/_index.md
Adds a link in the metrics doc to the grafana dashboard example.
Relates to https://github.com/goharbor/harbor/pull/14504#event-4745389578 and https://github.com/goharbor/harbor/issues/14441
> Add link to grafana example

- docs/build-customize-contribute/compile-guide.md
- docs/build-customize-contribute/use-make.md
Updates use of `GOBUILDIMAGE` variable and follows the Go version updated in the main repo (i.e., goharbor/harbor#13836) on build.
As https://goharbor.io/docs/2.2.0/build-customize-contribute/use-make/ describes the variable including `GOBUILDIMAGE` and examples with it, it does not look like https://goharbor.io/docs/2.2.0/build-customize-contribute/compile-guide/ requires newbies to specify `GOBUILDIMAGE` variable.
> Update use of GOBUILDIMAGE variable on build

- docs/administration/configure-proxy-cache/_index.md
The example command for pulling a single level or official image was missing the proxy project name before /library/.
> correct single level pull command

- docs/install-config/configure-user-settings-cli.md
Fix italian quotes in CONFIG_OVERWRITE_JSON example
> Fix: italian quotes in CONFIG_OVERWRITE_JSON example

- docs/administration/upgrade/_index.md
Based on the release notes for the upcoming 2.5 release, here is the updated upgrade doc.
I've also removed some old information and updated it to point folks to older upgrade pages depending on their version. Related to the info in this issue, https://github.com/goharbor/website/issues/304
> Add upgrade to 2.5 docs

- docs/administration/upgrade/_index.md
I assume the version number mismatch was due to a simple copy-paste error.
> Fix links to upgrade guides for previous versions

- Makefile
1. Bind host to 0.0.0.0 for `hugo server` command.  Then users can visit the server by `http://localhost:1313` or   `http://<ip>:1313`. The latter is often used for remote access
Signed-off-by: AllForNothing <sshijun@vmware.com>
> Bind host to 0.0.0.0

- docs/build-customize-contribute/registry-landscape.md
This PR updates some project Quay-related features in the registry landscape table.
Some differences have been found in the recent [overview](https://github.com/SovereignCloudStack/standards/pull/212/files) of the open-source container registries within the SCS project.
Find the list of modified Quay features and comments below:
1. _Content Trust and Validation_  
- Quay supports Cosign since [Quay v3.6](https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/use_red_hat_quay/oci-intro#cosign-oci-with-quay) 
- See the print screen from my quick test below: 
2. _Project Quotas (by storage consumption)_
- Support for quota management based on storage consumption is there since [Quay v3.7](https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/use_red_hat_quay/in …
> Update registry landscape table

- docs/install-config/configure-yml-file.md
In storage_service section `ed` of `disabled` missed.
‍`"‍` sign at the end of container name shall be removed.
Signed-off-by: SMHashemi <s.milad.hashemi@gmail.com>
> `disabled` missed `ed` and `"` is  intercalary

- docs/administration/configure-authentication/oidc-auth.md
Adding a hint to login via DB in case overriding the primary configured OIDC is needed.
It's important to have it in docs, because if you cannot login you cannot read the info popup in settings.
> Adding hint for overriding OIDC

- docs/build-customize-contribute/compile-guide.md
The Harbor compile guide, step 3, configuration refers to a `make/harbor.yaml.tmp` file which does not exist the the harbor repo: 
- [website](https://goharbor.io/docs/edge/build-customize-contribute/compile-guide/)
- [github](https://github.com/goharbor/website/blob/main/docs/build-customize-contribute/compile-guide.md#step-3-building-and-installing-harbor)
The file is actually named [`make/harbor.yaml.tmpl`](https://github.com/goharbor/harbor/blob/main/make/harbor.yml.tmpl)
> Fix a typo in the compile guide

- docs/administration/configure-authentication/oidc-auth.md
1. Fixes https://github.com/goharbor/harbor/issues/19419
> Enhance the explanation for the group filter

- docs/administration/configure-proxy-cache/_index.md
Hello, 
I found a missing element in compatibility list in Configure Proxy Cache page.
Artifactory support has been added in this [PR](https://github.com/goharbor/harbor/pull/17738).
I fixed it and you might want backport in 2.9.0. 
Thank you !
> Missing artifactory in compatibility list in Configure Proxy Cache page

- docs/install-config/configure-yml-file.md
All the registry docs have moved to Distribution per https://docs.docker.com/registry/
> Fix link in storage docs to Docker Registry Configuration

- docs/administration/upgrade/_index.md
The release notes for harbor v2.9.0 state that postgres must be >= 12. Updating upgrade guide to match this
https://github.com/goharbor/harbor/releases/tag/v2.9.0
See issue https://github.com/goharbor/website/issues/536
> Correct minimum external postgres version requirement in upgrade for 2.10.0 docs

- docs/administration/upgrade/_index.md
The release notes for harbor v2.9.0 state that postgres must be >= 12. Updating upgrade guide to match this
https://github.com/goharbor/harbor/releases/tag/v2.9.0
See issue https://github.com/goharbor/website/issues/536
> Correct minimum external postgres version requirement in upgrade for 2.9.0 docs 

- docs/administration/upgrade/_index.md
The release notes for harbor v2.9.0 state that postgres must be >= 12. Updating upgrade guide to match this
https://github.com/goharbor/harbor/releases/tag/v2.9.0
See issue https://github.com/goharbor/website/issues/536
> Correct minimum external postgres version requirement in upgrade for edge docs

- layouts/partials/partners.html
- layouts/partials/users.html
This is a fix of the layout on the main page. 
The left side is the current setup and the right side is the new layout. 
What changes is the orientation of the images and the max size of images, so that we don't end up with images that are too small or too big.
> fix layout of users and partners

- docs/working-with-projects/working-with-images/sign-images.md
> Update sign-images.md removed duplicate text

- assets/sass/helpers.sass
Hi Harbor Community I added a style in the tables, with this change if the table width is big automatically adds an horizontal scrollbar. @OrlinVasilev
> feat: added style to add horizontal scrollbars on tables if are bigger

- docs/install-config/configure-yml-file.md
> fixing typo in the page configure-yml-file.md

- docs/administration/configuring-replication/create-replication-rules.md
The word "Source" was spelled "Soure"
> Fix spelling error

- content/blog/cosign-2.5.0.md
- layouts/partials/home/intro.html
Resolves issue #582 
Fixes Youtube iframe bleeding out in [homepage](https://goharbor.io/) and [cosign blog page](https://goharbor.io/blog/cosign-2.5.0/) when the page size is very small.
Also updates cosign blog page with new logo.
> Fix youtube frame not responsive

- docs/administration/vulnerability-scanning/configure-custom-certs.md
> fixing typo in the page configure-custom-certs page

- docs/working-with-projects/working-with-images/create-tag-immutability-rules.md
> fixing typo in the page create-tag-immutability-rules.md

- layouts/partials/home/intro.html
To be compliant with GDPR, CCPA and other major regulations, we need to use Youtube 'privacy-enhanced mode' for embedded video on website.
> Use 'privacy-enhanced mode' for Youtube video
